-- =====================================================================
-- Importação dos produtos do catálogo atual (Fase 2)
-- Gerado a partir do index.html em 2026-08-08 — 161 produtos.
-- catalog_code aqui é o código "01.01" etc. EXATAMENTE como aparece hoje
-- no catálogo publicado (mesma lógica de sectionCodes do index.html),
-- congelado a partir de agora — não muda mais sozinho por reordenação.
-- Rode este arquivo inteiro no SQL Editor do Supabase (projeto Rafa 3D).
-- Seguro rodar de novo: on conflict atualiza em vez de duplicar.
-- =====================================================================
insert into products (catalog_code, category, name, height_cm, sale_price, price_unit_note, promo_note, extra_note, image_path)
values
('01.01', 'products', 'Vaso Bloom', 18, 47.9, null, null, null, 'assets/p1.png'),
('01.02', 'products', 'Vaso Torcido de Folha', 18, 47.9, null, null, null, 'assets/p2.png'),
('01.03', 'products', 'Vaso de Parede (Cálice)', 13, 49.9, 'cada', null, null, 'assets/p3.png'),
('01.04', 'products', 'Vaso Serenora em Espiral (Elegante)', 20, 54.9, null, null, null, 'assets/p4.png'),
('01.05', 'products', 'Laço Quadrado (Vaso Canelado)', 18, 91.9, null, null, null, 'assets/p5.png'),
('01.06', 'products', 'Vaso Decorativo (Duplo)', 20, 79.9, null, null, null, 'assets/p6.png'),
('01.07', 'products', 'Vaso Torcido em Espiral (Cobre)', 20, 49.9, null, null, null, 'assets/p7.png'),
('01.08', 'products', 'Jarro Beija-flor Decorativo', 18, 84.9, null, null, null, 'assets/p8.png'),
('01.09', 'products', 'Vaso de Folha', 20, 47.9, 'cada', null, null, 'assets/p9.png'),
('01.10', 'products', 'Miniatura de Tartaruga (Vaso)', 10, 89.9, null, null, null, 'assets/p10.png'),
('01.11', 'products', 'Vaso de Flores (Ondulado)', 18, 44.9, null, null, null, 'assets/p11.png'),
('01.12', 'products', 'Vaso Octogonal Espiralado', 20, 47.9, null, null, null, 'assets/p12.png'),
('01.13', 'products', 'Vaso em Formato de Pinha', 18, 47.9, 'cada', null, null, 'assets/p13.png'),
('01.14', 'products', 'Vaso Vórtice (Decoração de Escritório)', 18, 44.9, null, null, null, 'assets/p14.png'),
('01.15', 'products', 'Vaso com Folhas Decorativas', 20, 52.9, null, null, null, 'assets/p15.png'),
('01.16', 'products', 'Vaso para Planta Artificial (Encaixe)', null, 42.9, null, null, null, 'assets/p16.png'),
('01.17', 'products', 'Vaso de Planta Dachshund', null, 49.9, null, null, null, 'assets/p17.png'),
('01.18', 'products', 'Vaso Filo — Elegância Moderna', null, 47.9, null, null, null, 'assets/p18.png'),
('01.19', 'products', 'Vaso Kairos Flux (Jarra)', null, 46.9, null, null, null, 'assets/p19.png'),
('01.20', 'products', 'Vaso Design Moderno', null, 47.9, null, null, null, 'assets/p20.png'),
('01.21', 'products', 'Vaso Espiral', null, 39.9, null, null, null, 'assets/p21.png'),
('01.22', 'products', 'Plantador Ninho', null, 59.9, 'cada', '3 por R$ 149,90', null, 'assets/p22.png'),
('01.23', 'products', 'Suporte de Planta Parede Minimalista', null, 46.9, null, null, null, 'assets/p23.png'),
('01.24', 'products', 'Vaso de Decoração Ousada', 20, 69.9, null, null, null, 'assets/p24.png'),
('01.25', 'products', 'Vaso Moderno em Espirais', 15, 54.9, null, null, null, 'assets/p25.png'),
('01.26', 'products', 'Bandeja Decorativa em Formato de Folha', null, 32.9, null, null, null, 'assets/p26.png'),
('01.27', 'products', 'Árvore do Amor', null, 14.9, null, null, null, 'assets/car19.png'),
('01.28', 'products', 'Expositor Home', null, 14.9, null, null, null, 'assets/car20.png'),
('02.01', 'cars', 'Carro AE86 Divertido', null, 64.9, null, null, null, 'assets/car1.png'),
('02.02', 'cars', 'Edição Futurista', null, 39.9, null, null, null, 'assets/car2.png'),
('02.03', 'cars', 'Cubo Antiestresse', null, 14.9, null, null, null, 'assets/car3.png'),
('02.04', 'cars', 'Conjunto Impossível de Passagem', null, 9.9, 'cada', null, 'escolha a letra', 'assets/car4.png'),
('02.05', 'cars', 'Katana Retrátil', null, 34.9, null, null, null, 'assets/car5.png'),
('02.06', 'cars', 'Sapo Saltador', null, 9.9, 'cada', null, null, 'assets/car6.png'),
('02.07', 'cars', 'Cubo Infinito', null, 19.9, 'cada', null, null, 'assets/car7.png'),
('02.08', 'cars', 'Cone Espiral Antiestresse', null, 19.9, null, null, null, 'assets/car8.png'),
('02.09', 'cars', 'Estrela Sensorial', null, 14.9, null, null, null, 'assets/car9.png'),
('02.10', 'cars', 'Jogo da Forca', null, 14.9, null, null, null, 'assets/car10.png'),
('02.11', 'cars', 'Pião Mágico Ilusório', null, 9.9, null, null, null, 'assets/car11.png'),
('02.12', 'cars', 'Polvo Articulado', null, 22.9, 'cada', null, null, 'assets/car12.png'),
('02.13', 'cars', 'Disco de Mesa', null, 39.9, null, null, null, 'assets/car13.png'),
('02.14', 'cars', 'Giroscópio e Mini Lançador', null, 39.9, null, null, null, 'assets/car14.png'),
('02.15', 'cars', 'Foguete de Pressão de Ar', null, 64.9, null, null, null, 'assets/car15.png'),
('02.16', 'cars', 'Jogo da Velha', null, 9.9, null, null, null, 'assets/car16.png'),
('02.17', 'cars', 'Suporte de Copos Articulado de Tartaruga', null, 59.9, null, null, null, 'assets/car17.png'),
('03.01', 'holders', 'Porta Card Pokémon (Branco e Vermelho)', null, 49.9, null, null, null, 'assets/holder2.png'),
('03.02', 'holders', 'Porta Card Pokémon (Dourado, Vermelho e Branco)', null, 89.9, null, null, null, 'assets/holder3.png'),
('03.03', 'holders', 'Porta Card Pokémon (50 a 125 figurinhas)', null, 44.9, null, null, null, 'assets/holder7.png'),
('03.04', 'holders', 'Porta Card Pokémon (Formato Pokébola Quadrada)', null, 49.9, 'cada', null, null, 'assets/holder8.png'),
('03.05', 'holders', 'Porta Card Pokémon Gaole', null, 79.9, null, null, null, 'assets/holder9.png'),
('03.06', 'holders', 'Porta Pokémon Grande (200 ou mais figurinhas)', null, 19.9, null, null, null, 'assets/holder10.png'),
('03.07', 'holders', 'Porta Card Pokémon Magro', null, 39.9, null, null, null, 'assets/holder11.png'),
('03.08', 'holders', 'Porta Card Pokémon com Trava', null, 39.9, null, null, null, 'assets/holder12.png'),
('03.09', 'holders', 'Porta Card Pokémon Clássico', null, 69.9, null, null, null, 'assets/holder13.png'),
('04.01', 'utils', 'Suporte Parafone e Controle de Videogame (PS5)', null, 24.9, null, null, null, 'assets/util1.png'),
('04.02', 'utils', 'Suporte para Fone de Ouvido e Controle', null, 64.9, null, null, null, 'assets/util2.png'),
('04.03', 'utils', 'Suporte Alexa Greifer', null, 19.9, null, null, null, 'assets/util3.png'),
('04.04', 'utils', 'Suporte de Parede para Alexa', null, 14.9, null, null, null, 'assets/util4.png'),
('04.05', 'utils', 'Suporte de Escova de Dentes (Formato de Dente)', null, 24.9, null, null, null, 'assets/util5.png'),
('04.06', 'utils', 'Suporte para Papel Higiênico', null, 59.9, null, null, null, 'assets/util6.png'),
('04.07', 'utils', 'Suporte de Gato para Alexa', null, 124.9, null, null, null, 'assets/util7.png'),
('04.08', 'utils', 'Suporte para Carregador', null, 9.9, null, null, null, 'assets/util8.png'),
('04.09', 'utils', 'Caixa Organizadora de Controle Remoto com Laço', null, 74.9, null, null, null, 'assets/util9.png'),
('04.10', 'utils', 'Organizador de Controle Remoto', null, 74.9, null, null, null, 'assets/util10.png'),
('04.11', 'utils', 'Organizador de Controle Remoto II', null, 44.9, null, null, null, 'assets/util11.png'),
('04.12', 'utils', 'Organizador de Controle Remoto III', null, 39.9, null, null, null, 'assets/util12.png'),
('04.13', 'utils', 'Organizador de Controle Remoto IV', null, 99.9, null, null, null, 'assets/util13.png'),
('04.14', 'utils', 'Suporte de Canecas', null, 79.9, null, null, null, 'assets/util15.png'),
('04.15', 'utils', 'Suporte de Garrafas de Geladeira (Par, para 2 garrafas)', null, 19.9, null, null, null, 'assets/util16.png'),
('04.16', 'utils', 'Gancho de Parede Resistente', null, 19.9, null, null, null, 'assets/util17.png'),
('04.17', 'utils', 'Cine-Companion', null, 84.9, null, null, null, 'assets/util18.png'),
('04.18', 'utils', 'Descanso de Utensílios Minimalista', null, 19.9, null, null, null, 'assets/util19.png'),
('04.19', 'utils', 'Porta Esponja (Somente o Suporte)', null, 64.9, null, null, null, 'assets/util20.png'),
('04.20', 'utils', 'Dispensador de Ovos', null, 79.9, null, null, null, 'assets/util21.png'),
('04.21', 'utils', 'Grampo em G', null, 24.9, 'cada', null, null, 'assets/util22.png'),
('04.22', 'utils', 'Transportador de Sacola de Supermercado', null, 19.9, null, null, null, 'assets/util23.png'),
('04.23', 'utils', 'Lavador Inteligente de Frutas e Legumes (HydroBowl)', null, 134.9, null, null, null, 'assets/util25.png'),
('04.24', 'utils', 'Porta Guardanapo I', null, 29.9, null, null, null, 'assets/util31.png'),
('04.25', 'utils', 'Suporte de Aranha para Alexa', null, 29.9, null, null, null, 'assets/car18.png'),
('05.01', 'wines', 'Suporte de Lagartixa para Vinho', null, 29.9, null, null, null, 'assets/car21.png'),
('05.02', 'wines', 'Suporte de Gato para Vinho', null, 34.9, null, null, null, 'assets/car22.png'),
('05.03', 'wines', 'Suporte de Vinhos', null, 89.9, null, null, null, 'assets/wine3.png'),
('05.04', 'wines', 'Suporte de Coelho para Vinho', null, 99.9, null, null, null, 'assets/wine4.png'),
('05.05', 'wines', 'Suporte de Vinho em Formato de Chama', null, 64.9, null, null, null, 'assets/wine5.png'),
('05.06', 'wines', 'Suporte para Vinhos', null, 139.9, null, null, null, 'assets/wine6.png'),
('05.07', 'wines', 'Porta Latas Monster', null, 64.9, null, null, null, 'assets/util14.png'),
('05.08', 'wines', 'Suporte de Lata I', null, 64.9, null, null, null, 'assets/wine8.png'),
('05.09', 'wines', 'Suporte de Cavalo para Vinho', null, 119.9, null, null, null, 'assets/wine9.png'),
('06.01', 'keychains', 'Chaveiro de Porquinho', null, 27.9, null, null, null, 'assets/key1.png'),
('06.02', 'keychains', 'Chaveiro de Coelhinho', null, 27.9, null, null, null, 'assets/key2.png'),
('06.03', 'keychains', 'Chaveiro de Patinho (com ou sem perninha)', null, 29.9, null, null, null, 'assets/key3.png'),
('06.04', 'keychains', 'Chaveiro de Ovelhinha', null, 27.9, null, null, null, 'assets/key4.png'),
('06.05', 'keychains', 'Chaveiro de Sapinho', null, 27.9, null, null, null, 'assets/key5.png'),
('06.06', 'keychains', 'Chaveiro de Caranguejinho', null, 24.9, null, null, null, 'assets/key6.png'),
('06.07', 'keychains', 'Chaveiro de Dinossaurinho', null, 24.9, null, null, null, 'assets/key7.png'),
('06.08', 'keychains', 'Chaveiro de Raposinha', null, 29.9, null, null, null, 'assets/key8.png'),
('06.09', 'keychains', 'Chaveiro de Axolote', null, 27.9, null, null, null, 'assets/key9.png'),
('06.10', 'keychains', 'Chaveiro de Jacaré', null, 27.9, 'cada', null, null, 'assets/key10.png'),
('06.11', 'keychains', 'Chaveiro de Tartaruga', null, 32.9, 'cada', null, null, 'assets/key11.png'),
('06.12', 'keychains', 'Chaveiro de Cavalinho', null, 24.9, 'cada', null, null, 'assets/key12.png'),
('06.13', 'keychains', 'Chaveiro de Lobinho', null, 32.9, 'cada', null, null, 'assets/key13.png'),
('06.14', 'keychains', 'Chaveiro de Orca', null, 27.9, 'cada', null, null, 'assets/key14.png'),
('06.15', 'keychains', 'Chaveiro de Crocodilo', null, 24.9, null, null, null, 'assets/key15.png'),
('06.16', 'keychains', 'Chaveiro de Cavalo', null, 24.9, null, null, null, 'assets/key16.png'),
('06.17', 'keychains', 'Chaveiro de Dragãozinho', null, 24.9, null, null, null, 'assets/key17.png'),
('06.18', 'keychains', 'Chaveiro de Axolote I', null, 14.9, null, null, null, 'assets/key18.png'),
('06.19', 'keychains', 'Chaveiro de Bola de Futebol', null, 19.9, null, null, null, 'assets/key19.png'),
('06.20', 'keychains', 'Chaveiro de Bola de Basquete', null, 19.9, 'cada', null, null, 'assets/key20.png'),
('06.21', 'keychains', 'Chaveiro de Bola de Vôlei', null, 19.9, null, null, null, 'assets/key21.png'),
('06.22', 'keychains', 'Chaveiro de Bola de Tênis', null, 19.9, null, null, null, 'assets/key22.png'),
('06.23', 'keychains', 'Chaveiro de Bola de Beisebol', null, 24.9, null, null, null, 'assets/key23.png'),
('06.24', 'keychains', 'Chaveiro de Bola de Golfe', null, 14.9, null, null, null, 'assets/key24.png'),
('06.25', 'keychains', 'Chaveiro de Bola de Futebol Americano', null, 14.9, 'cada', null, null, 'assets/key25.png'),
('06.26', 'keychains', 'Chaveiro de Bola de Sinuca', null, 19.9, null, null, null, 'assets/key26.png'),
('06.27', 'keychains', 'Chaveiro do Mew', null, 19.9, null, null, null, 'assets/key27.png'),
('06.28', 'keychains', 'Chaveiro do Charmander', null, 24.9, 'cada', null, null, 'assets/key28.png'),
('06.29', 'keychains', 'Chaveiro de Pokébola', null, 15.9, null, null, null, 'assets/key29.png'),
('06.30', 'keychains', 'Chaveiro do Pikachu', null, 19.9, null, null, null, 'assets/key30.png'),
('06.31', 'keychains', 'Chaveiro do Lucario (70mm)', null, 24.9, null, null, null, 'assets/key31.png'),
('06.32', 'keychains', 'Chaveiro das Evoluções do Eevee', null, 14.9, 'cada', null, null, 'assets/key32.png'),
('06.33', 'keychains', 'Chaveiro do Mewtwo', null, 24.9, null, null, null, 'assets/key33.png'),
('06.34', 'keychains', 'Chaveiro de Chapéu do Luffy', null, 14.9, null, null, null, 'assets/key34.png'),
('06.35', 'keychains', 'Chaveiros de One Piece Coleção', null, 14.9, 'cada', null, null, 'assets/key35.png'),
('06.36', 'keychains', 'Chaveiro de Dragon Ball', null, 15.9, null, null, null, 'assets/key36.png'),
('06.37', 'keychains', 'Chaveiro de Dragon Ball Coleção', null, 14.9, 'cada', null, null, 'assets/key37.png'),
('06.38', 'keychains', 'Chaveiro do Naruto Comendo', null, 16.9, null, null, null, 'assets/key38.png'),
('06.39', 'keychains', 'Chaveiro do Naruto Coleção', null, 12.9, 'cada', null, null, 'assets/key39.png'),
('06.40', 'keychains', 'Chaveiro de Café', null, 14.9, null, null, null, 'assets/key40.png'),
('07.01', 'phoneStands', 'Suporte de Carregamento de Celular de Parede', null, 14.9, null, null, null, 'assets/util26.png'),
('07.02', 'phoneStands', 'Suporte de Celular', null, 14.9, null, null, null, 'assets/util27.png'),
('07.03', 'phoneStands', 'Suporte para Celular III', null, 16.9, null, null, null, 'assets/util28.png'),
('07.04', 'phoneStands', 'Suporte de Celular IV', null, 39.9, null, null, null, 'assets/util29.png'),
('07.05', 'phoneStands', 'Suporte para Celular V', null, 64.9, 'cada', null, null, 'assets/util30.png'),
('08.01', 'deskOrganizers', 'Organizador de Mesa I', null, 54.9, null, null, null, 'assets/desk1.png'),
('08.02', 'deskOrganizers', 'Organizador de Mesa II (Post-it)', null, 29.9, null, null, null, 'assets/desk2.png'),
('08.03', 'deskOrganizers', 'Organizador de Mesa III (Giratório)', null, 39.9, null, null, null, 'assets/desk3.png'),
('08.04', 'deskOrganizers', 'Porta Caneta em Formato de Saco de Papel', null, 24.9, null, null, null, 'assets/desk4.png'),
('09.01', 'books', 'Marca Páginas Coleção', null, 19.9, 'cada', null, null, 'assets/util32.png'),
('09.02', 'books', 'Marca Páginas de Zíper', null, 19.9, null, null, null, 'assets/book2.png'),
('09.03', 'books', 'Marcador de Páginas de Homenzinho II', null, 19.9, null, null, null, 'assets/book3.png'),
('09.04', 'books', 'Marca Páginas de Gato III', null, 19.9, null, null, null, 'assets/book4.png'),
('09.05', 'books', 'Suporte para Páginas de Livros', null, 12.9, null, null, null, 'assets/book5.png'),
('09.06', 'books', 'Prateleira de Parede para Livros Inclinada (Par)', null, 59.9, null, null, null, 'assets/util24.png'),
('10.01', 'minis', 'Action Figure do Batman', null, 34.9, null, null, null, 'assets/mini1.png'),
('10.02', 'minis', 'Action Figure do Pantera Negra', null, 34.9, null, null, null, 'assets/mini2.png'),
('10.03', 'minis', 'Todas as Formas do Mecha Chameleon', null, 39.9, null, null, null, 'assets/mini3.png'),
('10.04', 'minis', 'Action Figure do Cão Covarde', null, 84.9, null, null, null, 'assets/mini_cao_covarde.jpg'),
('10.05', 'minis', 'Action Figure da Pantera Cor-de-Rosa', null, 39.9, null, null, null, 'assets/mini_pantera_rosa.jpg'),
('10.06', 'minis', 'Action Figure do Scooby Doo', null, 89.9, null, null, null, 'assets/mini_scooby_doo.jpg'),
('10.07', 'minis', 'Action Figure da Hornet', null, 39.9, null, null, null, 'assets/mini_hornet.jpg'),
('10.08', 'minis', 'Action Figure do Pluto', null, 64.9, null, null, null, 'assets/mini_pluto.jpg'),
('10.09', 'minis', 'Action Figure do Patolino', null, 64.9, null, null, null, 'assets/mini_patolino.jpg'),
('10.10', 'minis', 'Action Figure do Pinky', null, 54.9, null, null, null, 'assets/mini_pinky.jpg'),
('10.11', 'minis', 'Action Figure do Cérebro', null, 54.9, null, null, null, 'assets/mini_cerebro.jpg'),
('10.12', 'minis', 'Action Figure do Lula Molusco', null, 39.9, null, null, null, 'assets/mini_lula_molusco.jpg'),
('10.13', 'minis', 'Action Figure do Plankton', null, 39.9, null, null, null, 'assets/mini_plankton.jpg'),
('10.14', 'minis', 'Action Figure de Patrick', null, 39.9, null, null, null, 'assets/mini_patrick.jpg'),
('10.15', 'minis', 'Action Figure do Jake', null, 39.9, null, null, null, 'assets/mini_jake.jpg'),
('10.16', 'minis', 'Action Figure do Tio Patinhas', null, 44.9, null, null, null, 'assets/mini_tio_patinhas.jpg'),
('10.17', 'minis', 'Action Figure do Gary', null, 44.9, null, null, null, 'assets/mini_gary.jpg'),
('10.18', 'minis', 'Action Figure do Bob Esponja', null, 39.9, null, null, null, 'assets/mini_bob_esponja.jpg')
on conflict (catalog_code) do update set
  category = excluded.category,
  name = excluded.name,
  height_cm = excluded.height_cm,
  sale_price = excluded.sale_price,
  price_unit_note = excluded.price_unit_note,
  promo_note = excluded.promo_note,
  extra_note = excluded.extra_note,
  image_path = excluded.image_path,
  updated_at = now();
